project:
  type: website
  execute-dir: project
  render:
    - "*.qmd"

website:
  title: "Performance examples in Julia"
  site-url: "https://pnavaro.github.io/math-julia"
  repo-url: https://github.com/pnavaro/math-julia
  repo-branch: "master"
  repo-actions: source
  page-navigation: true
  navbar:
    search: true
    type: dark
    background: primary
    left:
      - icon: github
        href: https://github.com/pnavaro/math-julia
        aria-label: GitHub

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

