project:
  type: website
  execute-dir: project
  render:
    - "*.qmd"

website:
  title: Scientific computing with Julia
  site-url: https://pnavaro.github.io/math-julia
  repo-url: https://github.com/pnavaro/math-julia
  repo-branch: master
  repo-actions: source
  page-navigation: true
  navbar:
    search: true
    type: dark
    background: primary
    left:
      - icon: github
        href: https://github.com/pnavaro/math-julia
        aria-label: GitHub
  sidebar:
    contents:
      - section: "Introduction"
        contents:
          - href: basis/index.qmd
      - section: "Performance"
        contents:
          - href: performance/index.qmd
          - href: performance/01-put-code-inside-function.qmd
          - href: performance/02-avoid-untyped-global-variable.qmd
          - href: performance/03-pay-attention-to-memory-allocation.qmd
          - href: performance/04-avoid-containers-with-abstract-type.qmd
          - href: performance/05-avoid-struct-fields-with-abstract-type.qmd
          - href: performance/06-break-functions-into-multiple-definitions.qmd
          - href: performance/07-write-type-stable-functions.qmd
          - href: performance/08-avoid-changing-the-type-of-a-variable.qmd
          - href: performance/09-access-arrays-in-memory-order.qmd
          - href: performance/10-preallocating-outputs.qmd
          - href: performance/11-fused-vectorized-operations.qmd
          - href: performance/12-consider-using-views-for-slices.qmd
          - href: performance/13-copy-irregularly-accessed-data.qmd
          - href: performance/14-consider-static-arrays.qmd
          - href: performance/15-avoid-string-interpolation-for-io.qmd
          - href: performance/16-performance-annotations.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    execute:
       enabled: false

