project:
  type: website
  execute-dir: project
  render:
    - "*.qmd"

website:
  title: Scientific computing with Julia
  site-url: https://pnavaro.github.io/math-julia
  repo-url: https://github.com/pnavaro/math-julia
  repo-branch: master
  repo-actions: source
  page-navigation: true
  navbar:
    search: true
    type: dark
    background: primary
    left:
      - icon: github
        href: https://github.com/pnavaro/math-julia
        aria-label: GitHub
  sidebar:
    contents:
      - section: "Introduction"
        contents:
          - href: basics/index.qmd
      - section: "Performance"
        contents:
          - href: performance/put-code-inside-function.qmd
          - href: performance/pay-attention-to-memory-allocation.qmd
          - href: performance/when-avoid-abstract-type.qmd
          - href: performance/write-type-stable-functions.qmd
          - href: performance/access-arrays-in-memory-order.qmd
          - href: performance/vectorized-operations.qmd
          - href: performance/consider-static-arrays.qmd
          - href: performance/good-practices-for-io.qmd
          - href: performance/performance-annotations.qmd
      - section: "Differential equations"
        contents:
          - href: diffeq/runge-kutta.qmd
          - href: diffeq/poisson-equation.qmd
          - href: diffeq/rotation-with-fft.qmd
          - href: diffeq/gpu.qmd
      - text: "References"
        href: "references.qmd"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    execute:
       enabled: false

