project:
  type: website
  execute-dir: project
  render:
    - index.qmd
    - perf*.qmd

website:
  title: "Performance tips in Julia"
  site-url: "https://pnavaro.github.io/math-julia"
  navbar:
    type: dark
    background: primary
    left:
      - icon: github
        href: https://github.com/pnavaro/math-julia

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
  revealjs:
    theme: sky
    logo: images/irmar_0.png
    echo: true
    code-line-numbers: false
    footer: "[home](/index.html)"

