on:
  push:
    branches: master

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        
      - name: Install IJulia
        run: julia -e 'using Pkg; Pkg.add("IJulia"); Pkg.build("IJulia")'
      
      - name: Install Julia dependencies
        run: julia --project -e 'using Pkg; Pkg.instantiate()'

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      
      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
